# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

GPCW <- function(mcmc_samples, y, x, z, metrop_var_phi_trans, likelihood_indicator, offset = NULL, trials = NULL, a_r_prior = NULL, b_r_prior = NULL, a_sigma2_epsilon_prior = NULL, b_sigma2_epsilon_prior = NULL, sigma2_beta_prior = NULL, a_sigma2_theta_prior = NULL, b_sigma2_theta_prior = NULL, a_phi_prior = NULL, b_phi_prior = NULL, r_init = NULL, sigma2_epsilon_init = NULL, beta_init = NULL, theta_init = NULL, sigma2_theta_init = NULL, phi_init = NULL) {
    .Call(`_GPCW_GPCW`, mcmc_samples, y, x, z, metrop_var_phi_trans, likelihood_indicator, offset, trials, a_r_prior, b_r_prior, a_sigma2_epsilon_prior, b_sigma2_epsilon_prior, sigma2_beta_prior, a_sigma2_theta_prior, b_sigma2_theta_prior, a_phi_prior, b_phi_prior, r_init, sigma2_epsilon_init, beta_init, theta_init, sigma2_theta_init, phi_init)
}

beta_update <- function(x, z, off_set, sigma2_beta, w, gamma, theta_old) {
    .Call(`_GPCW_beta_update`, x, z, off_set, sigma2_beta, w, gamma, theta_old)
}

neg_two_loglike_update <- function(y, x, z, off_set, tri_als, likelihood_indicator, r, sigma2_epsilon, beta, theta) {
    .Call(`_GPCW_neg_two_loglike_update`, y, x, z, off_set, tri_als, likelihood_indicator, r, sigma2_epsilon, beta, theta)
}

phi_update <- function(a_phi, b_phi, temporal_corr_info, theta, sigma2_theta, phi_old, metrop_var_phi_trans, acctot_phi_trans) {
    .Call(`_GPCW_phi_update`, a_phi, b_phi, temporal_corr_info, theta, sigma2_theta, phi_old, metrop_var_phi_trans, acctot_phi_trans)
}

r_update <- function(y, x, z, off_set, a_r, b_r, beta, theta) {
    .Call(`_GPCW_r_update`, y, x, z, off_set, a_r, b_r, beta, theta)
}

rcpp_pgdraw <- function(b, c) {
    .Call(`_GPCW_rcpp_pgdraw`, b, c)
}

sigma2_epsilon_update <- function(y, x, z, a_sigma2_epsilon, b_sigma2_epsilon, beta_old, theta_old) {
    .Call(`_GPCW_sigma2_epsilon_update`, y, x, z, a_sigma2_epsilon, b_sigma2_epsilon, beta_old, theta_old)
}

sigma2_theta_update <- function(a_sigma2_theta, b_sigma2_theta, theta, corr_inv) {
    .Call(`_GPCW_sigma2_theta_update`, a_sigma2_theta, b_sigma2_theta, theta, corr_inv)
}

temporal_corr_fun <- function(p_z, phi) {
    .Call(`_GPCW_temporal_corr_fun`, p_z, phi)
}

theta_update <- function(x, z, off_set, w, gamma, beta, sigma2_theta_old, corr_inv) {
    .Call(`_GPCW_theta_update`, x, z, off_set, w, gamma, beta, sigma2_theta_old, corr_inv)
}

w_update <- function(y, x, z, off_set, tri_als, likelihood_indicator, r, beta_old, theta_old) {
    .Call(`_GPCW_w_update`, y, x, z, off_set, tri_als, likelihood_indicator, r, beta_old, theta_old)
}

